# -*- coding: utf-8 -*-
"""06. 파이썬 - 예외처리.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SoQifAS9Gz9vtZvAXR3bHwiDEcxhi308

# 예외처리

구문 오류 : 코드의 문법적 잘못에 의해 발생하는 오류

런타임 오류 : 실행 시점에 발생하는 오류
"""

# 구문 오류 예
print("hello)

num1 = int(input("정수 : "))
num2 = int(input("정수 : "))
print(num1/num2)

"""예외를 확인하여 원하는 형태로 처리하기"""

num1 = int(input("정수 : "))
num2 = int(input("정수 : "))
try:
  print(num1/num2)
except:
  print("예외가 발생했어요.")

num1 = int(input("정수 : "))
num2 = int(input("정수 : "))
try:
  print(num1/num2)
except:
  pass
print("yahoo")

num1 = int(input("정수 : "))
num2 = int(input("정수 : "))
try:
  print(num1/num2)
except: # 예외 발생 시
  print("음냐뤼")
else: # 그외
  print("수고하셨습니다.")
finally: # 어떤 상황이었든 최종적으로 실행
  print("허거덕")

"""예외 개체 사용"""

try:
  num1 = int(input("정수 : "))
  num2 = int(input("정수 : "))
  print(num1/num2)
except Exception as ex:
  print(ex)
  print(type(ex))
else:
  print("수고하셨습니다.")

try:
  num1 = int(input("정수 : "))
  num2 = int(input("정수 : "))
  print(num1/num2)
  ls = [1, 2, 3]
  n = int(input("1~3 중에 고르세요 : "))
  print(ls[n-1])
except ValueError as ex:
  print("입력한 값에 문제가 있습니다 :", ex)
except ZeroDivisionError:
  print("젯수가 0입니다.")
except Exception:
  print("어딘가 문제가 있네요.")
else:
  print("수고하셨습니다.")

"""# 예외를 발생시키기"""

def getsum(start, end, step=1):
  if start > end:
    raise ValueError
  s = 0
  for i in range(start, end+1, step):
    s += i
  return s

try:
  print(getsum(2, 10))
  print(getsum(10, 2))
except:
  print("예외 발생")